#all: obj/main.o

obj/main.o: src/main.cpp
	g++ -c src/main.cpp -o obj/main.o

#obj/Particula.o: src/Particula.cpp
#	g++ -c src/Particula.cpp -o obj/Particula.o
#obj/%.o: src/%.cpp
#	g++ -c $< -o $@

clean:
	@rm obj/*
